
export const corps=[
    
        {
            name:'Epaules',
            un:'Le développé militaire (military press) est un exercice qui permet de solliciter les muscles des épaules, des pectoraux, du haut du dos, des triceps et de la ceinture abdominale, ce qui en fait un exercice difficile pour les débutants.',
            deux:'Le développé Arnold (dumbbell Arnold press) est un exercice très efficace pour développer les muscles deltoïdes. Il s agit d une variante unique du développé épaules avec haltères, qui doit son nom au bodybuilder, acteur et gouverneur emblématique Arnold Schwarzenegger.',
            trois:'Le face pull est un exercice d isolation à la poulie qui permet de faire travailler principalement les épaules et secondairement le dos. Il cible spécifiquement les deltoïdes postérieurs (arrière des épaules), et sollicite aussi les rhomboïdes (les muscles qui vous permettent de serrer vos omoplates) et le milieu des trapèzes.',
            quatre:'Les élévations latérales à la poulie sont une variante très appréciée pour l entraînement des épaules. Il s agit d un exercice d isolation permettant de cibler précisément les muscles deltoïdes. Les élévations latérales peuvent également être effectuées avec des haltères ou une machine à élévation latérale.',
            cinq:'Les élévations latérales guidées à la machine permettent d isoler et de développer efficacement le chef latéral du deltoïde afin de lui donner cette largeur tant recherchée. ',
            six:'L exercice du développé épaules avec haltères est un excellent choix pour l entraînement des épaules. Il s agit d un exercice de base qui nécessite une bonne coordination.Bien sûr, il est aussi possible d effectuer cet exercice sur une barre de musculation, et on parle dans ce cas de développé militaire. Ceci dit, l utilisation d haltères, plutôt que d une barre, permet de travailler les muscles des épaules de façon équilibrée.',
            titreun:'MILITARY PRESS',
            titredeux:'DUMBBELL ARNOLD PRESS',
            titretrois:'FACE PULL',
            titrequatre:'ELEVATIONS LATERALES POULIE',
            titrecinq:'DELTOIDE',
            titresix:'HALTERES',
            image:require('../assets/images/épaules.png'),
            imageone:require('../assets/images/ep1.jpeg'),
            imagetwo:require('../assets/images/ep2.jpeg'),
            imagethree:require('../assets/images/ep3.jpeg'),
            imagefour:require('../assets/images/ep4.jpeg'),
            imagefive:require('../assets/images/ep5.jpeg'),
            imagesix:require('../assets/images/ep6.jpeg'),
          

          
            
        },
        {
            name:'Biceps',
            un:'L entraînement des biceps peut être relégué au second plan par rapport à des mouvements de force plus populaires comme le squat, le soulevé de terre et le développé couché.',
            deux:'Le curl concentré est un mouvement de la vieille école qui peut produire de vrais résultats, mais seulement si vous êtes prêt à travailler avec une bonne technique.',
            trois:'Le curl assis au pupitre barre EZ (en anglais curl Larry Scott, du nom de son inventeur) offre un certain nombre d avantages que vous ne trouverez peut-être pas dans un curl biceps classique. La conception de l exercice permet de concentrer l attention sur la partie négative de chaque répétition (lorsque vous redescendez la charge en position de départ). Cela favorise une forte connexion entre le cerveau et le muscle et maximise le temps sous tension ; deux aspects importants de la croissance musculaire.',
            quatre:'Le curl allongé à la poulie est un exercice qui isole parfaitement les biceps, mais également les avant-bras. En position allongée, votre corps ne peut pas se pencher vers l avant et utiliser l élan pour soulever la charge. Cela permet de maximiser le travail du biceps brachial.',
            cinq:'Cette variante du curl à la poulie (en anglais squatting cable curl) est un exercice qui permet de développer et renforcer les biceps, avec le corps en position de squat statique. ',
            six:'Les flexions de biceps avec une poulie en position debout sont un excellent exercice car, contrairement aux exercices avec des charges libres, elles permettent d obtenir une tension musculaire constante et, par conséquent, une plus forte contraction musculaire.',
            titreun:'SQUAT',
            titredeux:'CURL CONCENTRE',
            titretrois:'CURL ASSIS',
            titrequatre:'CURL ALLONGE',
            titrecinq:'CURL POULIE',
            titresix:'FLEXIONS BICEPS',
            image:require('../assets/images/biceps.jpeg'),
            imageone:require('../assets/images/bi1.jpeg'),
            imagetwo:require('../assets/images/bi2.jpeg'),
            imagethree:require('../assets/images/bi3.jpeg'),
            imagefour:require('../assets/images/bi4.jpeg'),
            imagefive:require('../assets/images/bi5.jpeg'),
            imagesix:require('../assets/images/bi6.jpeg'),
          
        },
        {
            name:"Triceps",
            un:'Il s agit d un exercice populaire dont le principal avantage est d obtenir un étirement très important du muscle, ce qui permet d activer davantage de fibres pour l hypertrophie musculaire.',
            deux:'L extension verticale des triceps à la barre (en anglais overhead tricep extension) est un exercice d isolation qui permet de développer la masse musculaire et la force des triceps, notamment la longue portion du triceps.',
            trois:'Les extensions des triceps à la machine (en anglais lever triceps extension) sont un excellent exercice pour isoler le muscle triceps brachial, le muscle composé de trois chefs situés à l arrière du bras.',
            quatre:'Cet exercice d isolation est parfait pour renforcer, développer et tonifier le triceps brachial, muscle situé à l arrière du bras.',
            cinq:'Il peut être difficile de mettre beaucoup de poids dans cet exercice, qui nécessite une grande stabilité du corps. Il est donc préférable de l utiliser comme un mouvement secondaire pour ceux qui cherchent à augmenter la masse musculaire de leurs pectoraux. Si vous avez des triceps puissants et peu de force aux pectoraux, il peut être intéressant d utiliser cet exercice pour pré-fatiguer les muscles de la poitrine.',
            six:'Les dips sont un des exercices de musculation les plus sous-estimés. Avec l abondance de machines disponibles pour travailler les bras, les épaules et les pectoraux, on a tendance à oublier certains exercices au poids de corps qui pourtant sont redoutablement efficaces.',
            titreun:'Le developpe militaire',
            titredeux:'OVERHEAD TRICEP',
            titretrois:'LEVER TRICEPS',
            titrequatre:'TRICEPS BRACHIAL',
            titrecinq:'MASSE MUSCULAIRE',
            titresix:'DIPS',
            image:require('../assets/images/triceps.jpg'),
            imageone:require('../assets/images/tri1.jpeg'),
            imagetwo:require('../assets/images/tri2.jpeg'),
            imagethree:require('../assets/images/tri3.jpeg'),
            imagefour:require('../assets/images/tri4.jpeg'),
            imagefive:require('../assets/images/tri5.jpeg'),
            imagesix:require('../assets/images/tri6.jpeg'),
            
        },
        {
            name:"Pectoraux",
            un:'Le développé couché est pratiqué comme un exercice pour le haut du corps, ciblant principalement les muscles pectoraux, et secondairement les triceps et épaules. Mais lorsqu il est effectué correctement, il permet de travailler tout le corps, avec une sollicitation des jambes, un gainage de la sangle abdominale, et une stabilisation de la ceinture scapulaire.',
            deux:' La variante inclinée (incline barbell bench press en anglais) va encore plus loin et met vraiment l accent sur le haut de la poitrine, près des clavicules. Il en résulte un aspect plus massif et esthétiquement plus complet de votre silhouette, ce qui est le but recherché lorsque vous souhaitez muscler les muscles pectoraux.',
            trois:'Le développé couché est considéré comme l exercice de base pour les pectoraux, mais il présente certaines limites. La principale limite est qu il ne s agit pas d un exercice pour les “pectoraux”. C est un exercice pour les pectoraux, les épaules et les triceps, qui fait appel à un mouvement composé (polyarticulaire) et qui ne permet pas de cibler efficacement un seul muscle.',
            quatre:'Les écartés à la poulie vis-à-vis (cable middle fly) sont une variante du Pec Deck ou Butterfly à la machine, un exercice pour renforcer les muscles pectoraux, et de l avant des épaules. L une des principales fonctions des muscles pectoraux est d amener vos bras en avant de votre corps, c est exactement ce que font les écartés.',
            cinq:'Le développé couché avec haltères (dumbbell bench press) est une variante du développé couché à la barre. C est un exercice qui permet de développer les muscles pectoraux.',
            six:'Le développé couché avec haltères (dumbbell bench press) est une variante du développé couché à la barre. C est un exercice qui permet de développer les muscles pectoraux.',
            titreun:'DEVELOPPE COUCHE',
            titredeux:'BARBELL BENCH PRESS',
            titretrois:'PECTORAUX',
            titrequatre:'MIDDLE FLY',
            titrecinq:'BENCH PRESS',
            titresix:'BENCH PRESS',
            image:require('../assets/images/Pecshead.jpg'),
            imageone:require('../assets/images/pec1.jpeg'),
            imagetwo:require('../assets/images/pec2.jpeg'),
            imagethree:require('../assets/images/pec3.jpeg'),
            imagefour:require('../assets/images/pec4.jpeg'),
            imagefive:require('../assets/images/pec5.jpeg'),
            imagesix:require('../assets/images/pec6.jpeg'),
            
        },
        {
            name:"Abdominaux",
            un:'La planche renforce en profondeur tous les muscles abdominaux. Les grands droits, les obliques internes et externes, les transverse sont intensément sollicités durant la planche. Cet exercice permet également de muscler le dos et les fessiers. En renforçant le gainage abdominal et dorsal, la colonne vertébrale est mieux stabilisée. La planche aide aussi à lutter contre le mal de dos.',
            deux:'Les crunchs sont un mouvement de base qui permet de cibler les muscles abdominaux, en particulier le muscle droit de l abdomen (le muscle du six-pack) et les obliques. Étant donné qu il ne nécessite pas de matériel ou de machine, c est un des premier exercice que l on effectue à la maison quand on veut “travailler les abdos”.',
            trois:'Le sit-up décliné, couramment appelé crunch décliné est une variante plus difficile du sit-up classique pour les abdominaux. Il s agit donc d un exercice à réserver à ceux qui ont une ceinture abdominale assez solide et l un des meilleurs exercices pour développer un impressionnant six-pack.',
            quatre:'Si vous avez déjà essayé de vous modeler des abdominaux solides, vous connaissez probablement les crunchs. Mais cet exercice à lui seul ne contribue que très peu à la formation de ces muscles.',
            cinq:'Le relevé de jambes à la chaise romaine (en anglais Captain s chair), effectué à l aide d un appareil de musculation appelé chaise romaine, est un exercice qui permet de renforcer les muscles abdominaux.',
            six:'La roue abdominale (en anglais “Ab Wheel” ou “Ab Roller“) est un accessoire “innocent” au premier abord, mais qui a une efficacité redoutable sur vos muscles abdominaux. Le renforcement de la sangle abdominale a des avantages pour tout type de sport, mais aussi pour la vie du quotidien.',
            titreun:'PLANCHE ',
            titredeux:'CRUNCHS',
            titretrois:'STIP UP',
            titrequatre:'CRUNCHS',
            titrecinq:'CAPTAIN CHAIR',
            titresix:'AB WHEEL OR AB ROLLER',
            image:require('../assets/images/abdominaux.jpeg'),
            imageone:require('../assets/images/abdo1.jpeg'),
            imagetwo:require('../assets/images/abdo2.jpeg'),
            imagethree:require('../assets/images/abdo3.jpeg'),
            imagefour:require('../assets/images/abdo4.jpeg'),
            imagefive:require('../assets/images/abdo5.jpeg'),
            imagesix:require('../assets/images/abdo6.jpeg'),
            
            
        },
        {
            name:"Dos",
            un:'Si vous êtes à la recherche d un exercice de musculation avancé pour le dos à inclure dans votre programme d entraînement, essayez les muscle-ups. Le muscle-up, également appelé muscle-up à la barre ou muscle-up strict, est un exercice qui utilise le poids du corps pour faire travailler un grand nombre de muscles du corps. C est l exercice de prédilection pour les pratiquants de street workout, CrossFit ou calisthenics.',
            deux:'La traction (en anglais pull up) est un exercice classique qui permet de cibler les muscles du haut du dos, en particulier le muscle grand dorsal.',
            trois:'Le tirage horizontal à la poulie (en anglais seated cable row) est un excellent exercice de musculation pour le dos, en particulier les muscles grands dorsaux, le milieu du dos et les trapèzes.',
            quatre:'Le rowing barre est un exercice composé qui fait travailler plusieurs groupes de muscles. Cet exercice fait travailler en particulier plusieurs muscles du dos, notamment le muscle grand dorsal (latissimus dorsi), le muscle sous-épineux (infraspinatus), les rhomboïdes, les muscles spinaux droits (erector spinae) et les muscles deltoïdes postérieurs (également appelés deltoïdes arrière).',
            cinq:'L exercice du shrug barre (en français haussements des épaules à la barre) est un très bon exercice pour développer les trapèzes. Il sollicite également les muscles abdominaux qui permettent au corps de rester droit.',
            six:'Le pull-over assis à la machine est un excellent exercice pour le dos, et plus particulièrement pour les muscles grands dorsaux qu il permet d isoler sur une très grande amplitude de mouvement. Cet exercice sollicite aussi dans une moindre mesure les muscles triceps et les muscles pectoraux.',
            titreun:'MUSCLE UPS',
            titredeux:'PULL UP',
            titretrois:'SEATED CABLE ROW',
            titrequatre:'ROWWING BARRE',
            titrecinq:'SHRUG BARRE',
            titresix:'PULL-OVER',
            image:require('../assets/images/dos.jpeg'),
            imageone:require('../assets/images/dos1.jpeg'),
            imagetwo:require('../assets/images/dos2.jpeg'),
            imagethree:require('../assets/images/dos3.jpeg'),
            imagefour:require('../assets/images/dos4.jpeg'),
            imagefive:require('../assets/images/dos5.jpeg'),
            imagesix:require('../assets/images/dos6.jpeg'),
            
            
        },
        {
            name:'Quadriceps',
            un:'La presse à cuisses inclinée (en anglais incline Leg Press) est un exercice composé très efficace qui permet de développer les muscles et la force des jambes. Les principaux muscles sollicités sont les quadriceps, mais les ischio-jambiers, les fessiers et les mollets sont également fortement stimulés en tant que muscles secondaires pendant l exercice.',
            deux:'Le squat est le roi de tous les exercices ! Bien qu il cible principalement les quadriceps, ischio-jambiers et fessiers, on dit qu il fait travailler plus de 256 muscles ! Que vous soyez bodybuilder, powerlifter ou sportif de compétition, le squat est un exercice composé incontournable qui devrait faire partie de tout programme de musculation.',
            trois:'Le leg extension est un exercice d isolation ciblant les quadriceps, composés de quatre muscles spécifiques situés à l avant de la cuisse : le droit fémoral, le vaste latéral, le vaste médial et le vaste intermédiaire.',
            quatre:'Les montées sur banc (dumbbell step up) sont un excellent exercice polyvalent pour le bas du corps.',   
            cinq:'Ce mouvement consiste à soulever une charge du sol jusqu au niveau des hanches sans utiliser d élan pour la monter. Il est connu comme l un des “trois grands” exercices pour les powerlifters, à savoir le squat, le développé couché et le soulevé de terre. Les culturistes utilisent le soulevé de terre pour stimuler la croissance musculaire de l ensemble de leur chaîne postérieure (muscles de l arrière du corps). En effet, le soulevé de terre fait principalement travailler les muscles des ischio-jambiers. Cependant, il s agit d un exercice composé complet qui sollicite également des muscles du dos, des fessiers, des quadriceps, des bras et des abdominaux.',
            six:'Le squat avant (front squat clean grip) est une variante du squat et un exercice utilisé pour travailler les muscles des jambes, et en particulier les muscles quadriceps.',
            titreun:'LEG PRESS',
            titredeux:'SQUAT',
            titretrois:'LEG EXTENSION',
            titrequatre:'DUMBBELL STEP UP',
            titrecinq:'SOULEVE TERRE',
            titresix:'FRONT SQUAT CLEAN GRIP',
            image:require('../assets/images/quadriceps.jpeg'),
            imageone:require('../assets/images/qua1.jpeg'),
            imagetwo:require('../assets/images/qua2.jpeg'),
            imagethree:require('../assets/images/qua3.jpeg'),
            imagefour:require('../assets/images/qua4.jpeg'),
            imagefive:require('../assets/images/qua5.jpeg'),
            imagesix:require('../assets/images/qua6.jpeg'),
            
            
        },
        {
            name:"Mollets",
            un:'Si vous souhaitez muscler vos mollets et que vous ne possédez pas la “donkey calf machine”, il est toujours possible de faire appel à un partenaire pour vous aider à reproduire cet exercice.',
            deux:'Si l objectif est de développer la masse musculaire des mollets, il est indispensable de soulever des charges lourdes. Les mollets sont généralement considérés comme le muscle le plus difficile à développer, car ils sont habitués à être constamment sollicités par le simple fait de se déplacer d un endroit à l autre. Les mollets sont capables d une quantité de travail particulièrement élevée.Pour obtenir des résultats en matière de force, de définition ou de volume des mollets, il faudra pour la plupart des gens faire preuve de force mentale et d une volonté forte et inébranlable',
            trois:'Les extensions des mollets assis avec barre (en anglais seated barbell calf raise) sont peu pratiquées, mais cela ne veut pas dire qu elles sont inefficaces. Il est certes relégué au second plan par rapport aux machines sophistiquées, mais il peut tout de même vous permettre de muscler vos mollets.C est un excellent moyen de varier d exercice si vous disposez d un équipement limité, comme une salle de musculation à la maison.',
            quatre:'Les élévations des mollets à la machine nommée Donkey (en anglais donkey calf machine) sont un exercice classique de musculation des mollets, popularisé par Arnold Schwarzenegger. Bien qu il le fasse en chargeant une ou deux partenaires de salle de sport sur son dos, voici une façon plus pratique de faire cette variante de montée des mollets',
            cinq:'Les extensions de mollets sur une machine de hack squat consistent essentiellement à effectuer une extension de mollets sur une machine de hack squat. Il existe plusieurs variantes de ce type de machines.',
            six:'Pour renforcer et développer vos mollets, vous avez besoin d exercices qui offrent un bon étirement en position basse. Cela permet une plus grande amplitude de mouvement. Par ailleurs, vous avez besoin de travailler avec des charges lourdes. Les élévations de mollets à la Smith machine répondent parfaitement à ces deux exigences.',
            titreun:'DONKEY CALF MACHINE',
            titredeux:'MASSE MUSCULAIRE',
            titretrois:'SEATED BARBELL CALF RAISE',
            titrequatre:'DONKEY',
            titrecinq:'HACK SQUAT',
            titresix:'SMITH MACHINE',
            image:require('../assets/images/mollets.jpg'),
            imageone:require('../assets/images/mo1.jpeg'),
            imagetwo:require('../assets/images/mo2.jpeg'),
            imagethree:require('../assets/images/mo3.jpeg'),
            imagefour:require('../assets/images/mo4.jpeg'),
            imagefive:require('../assets/images/mo5.jpeg'),
            imagesix:require('../assets/images/mo6.jpeg'),
            
            
        }, 
        
        
        {
            name:"Ischio-jambiers",
            un:'Le soulevé de terre jambes tendues est une variante du soulevé de terre qui permet de cibler principalement les muscles ischio-jambiers. C est un bon complément au squat, que l on peut effectuer dans la même séance.',
            deux:'La dorsiflexion des orteils (flexion vers le tibia) permet d isoler les ischio-jambiers, tandis que la flexion plantaire permet de solliciter aussi les muscles des mollets.Non seulement cet exercice augmentera la force du bas du corps, mais il vous aidera à prévenir les blessures en équilibrant la force et la masse musculaire acquise aux quadriceps.',
            trois:'La presse à cuisses inclinée (en anglais incline Leg Press) est un exercice composé très efficace qui permet de développer les muscles et la force des jambes. Les principaux muscles sollicités sont les quadriceps, mais les ischio-jambiers, les fessiers et les mollets sont également fortement stimulés en tant que muscles secondaires pendant l exercice.',
            quatre:'Le squat est le roi de tous les exercices ! Bien qu il cible principalement les quadriceps, ischio-jambiers et fessiers, on dit qu il fait travailler plus de 256 muscles ! Que vous soyez bodybuilder, powerlifter ou sportif de compétition, le squat est un exercice composé incontournable qui devrait faire partie de tout programme de musculation.',
            cinq:'L exercice good morning est un exercice efficace pour cibler les fessiers et les muscles ischio-jambiers.',
            six:'Le soulevé de terre roumain a longtemps été considéré comme la variante du soulevé de terre pour les jambes, bien que tous les mouvements d articulation de la hanche ciblent principalement les ischio-jambiers. Une idée judicieuse, pour augmenter la fréquence d entraînement et travailler sur la technique du mouvement, serait d effectuer du soulevé de terre roumain le jour des jambes et une autre variante du soulevé de terre le jour du dos ou des tractions.',
            titreun:'SOULEVE TERRE JAMBES',
            titredeux:'DORSIFLEXION ',
            titretrois:'LEG PRESS',
            titrequatre:'SQUAT',
            titrecinq:'GOOD MORNING',
            titresix:'Romanian Deadlift',
            image:require('../assets/images/ischio.jpeg'),
            imageone:require('../assets/images/is1.jpeg'),
            imagetwo:require('../assets/images/is2.jpeg'),
            imagethree:require('../assets/images/is3.jpeg'),
            imagefour:require('../assets/images/is4.jpeg'),
            imagefive:require('../assets/images/is5.jpeg'),
            imagesix:require('../assets/images/is6.jpeg'),
            
            
        },
 
       
        {
            name:"Fessiers",
            un:'Si vous cherchez un bon exercice pour travailler vos fessiers et le haut de vos jambes, le hip thrust est idéal pour votre programme d entraînement. Bien que vous puissiez effectuer cet exercice au poids du corps ou avec une barre, l utilisation d un appareil dédié aux mouvements de flexion des hanches vous permettra de rester stable et de travailler confortablement. Il peut être intimidant d essayer un nouvel appareil de musculation si vous ne l avez jamais utilisé auparavant, mais ne vous tracassez pas et testez cet exercice que vous pourriez vraiment adorer.',
            deux:'Le squat est le roi de tous les exercices ! Bien qu il cible principalement les quadriceps, ischio-jambiers et fessiers, on dit qu il fait travailler plus de 256 muscles ! Que vous soyez bodybuilder, powerlifter ou sportif de compétition, le squat est un exercice composé incontournable qui devrait faire partie de tout programme de musculation.',
            trois:'Le soulevé de terre roumain (RDL de l anglais Romanian Deadlift) est un exercice populaire et efficace pour la chaîne postérieure. Les bodybuilders l utilisent pour renforcer leurs fessiers et leurs ischio-jambiers, tandis que les powerlifters s en servent pour augmenter leurs performances au deadlift. Le RDL devrait faire partie de votre liste d exercices à faire régulièrement !',
            quatre:'L exercice good morning est un exercice efficace pour cibler les fessiers et les muscles ischio-jambiers.',
            cinq:'Le pull through à la poulie est un excellent exercice qui permet de travailler les puissants muscles de la chaîne postérieure. Il cible principalement les fessiers, et sollicite aussi les ischio-jambiers et les muscles bas du dos.',
            six:'Les montées sur banc (dumbbell step up) sont un excellent exercice polyvalent pour le bas du corps.',
            titreun:'HIP THRUST',
            titredeux:'SQUAT',
            titretrois:'ROMANIAN DEADLIFT',
            titrequatre:'GOOD MORNING',
            titrecinq:'PULL THROUGH',
            titresix:'DUMBBELL STEPUP',
            image:require('../assets/images/fessiers.jpeg'),
            imageone:require('../assets/images/fe1.jpeg'),
            imagetwo:require('../assets/images/fe2.jpeg'),
            imagethree:require('../assets/images/fe3.jpeg'),
            imagefour:require('../assets/images/fe4.jpeg'),
            imagefive:require('../assets/images/fe5.jpeg'),
            imagesix:require('../assets/images/fe6.jpeg'),
            
        }
    
    
]

